In [ ]:
# this model is used to predict whether based on the data a student will pass or fail

## IMPORTING DATASET

In [2]:
import pandas as pd
df=pd.read_csv("C:\\Users\goura\Downloads\Student_Performance.csv")

In [3]:
df.head()

,student_id,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,math_score,science_score,english_score,overall_score,final_grade
0,1,14,male,public,post graduate,3.1,84.3,yes,<15 min,yes,notes,42.7,55.4,57.0,53.1,e
1,2,18,female,public,graduate,3.7,87.8,yes,>60 min,no,textbook,57.6,68.8,64.8,61.3,d
2,3,17,female,private,post graduate,7.9,65.5,no,<15 min,no,notes,84.8,95.0,79.2,89.6,b
3,4,16,other,public,high school,1.1,58.1,no,15-30 min,no,notes,44.4,27.5,54.7,41.6,e
4,5,16,female,public,high school,1.3,61.0,yes,30-60 min,yes,group study,8.9,32.7,30.0,25.4,f

## PREPROCESSING THE DATA
the task asks us to predict whether a student will pass or fail based on the number of hours he/she studies,attendence and marks.
so this dataset needs to be minimised and preprocessed.

In [4]:
# selecting a handful of columns columns 
df = df[['student_id', 'study_hours', 'attendance_percentage', 'overall_score', 'final_grade']]

In [5]:
df.head()

   student_id  study_hours  attendance_percentage  overall_score final_grade
0           1          3.1                   84.3           53.1           e
1           2          3.7                   87.8           61.3           d
2           3          7.9                   65.5           89.6           b
3           4          1.1                   58.1           41.6           e
4           5          1.3                   61.0           25.4           f

we are trying to predict pass or fail but the final grade columns has ranges varying from a-f, so
i think its better to leave F as 0 and  then try to classify the rest as 1 (a-e)

In [6]:
df['final_grade'] = df['final_grade'].replace('f', 0)
df['final_grade'] = df['final_grade'].replace(['a','b','c','d','e'], 1)

C:\Users\goura\AppData\Local\Temp\ipykernel_16908\2189868038.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['final_grade'] = df['final_grade'].replace(['a','b','c','d','e'], 1)

In [7]:
df.head()

   student_id  study_hours  attendance_percentage  overall_score  final_grade
0           1          3.1                   84.3           53.1            1
1           2          3.7                   87.8           61.3            1
2           3          7.9                   65.5           89.6            1
3           4          1.1                   58.1           41.6            1
4           5          1.3                   61.0           25.4            0

In [8]:
print(df)

       student_id  study_hours  attendance_percentage  overall_score  \
0               1          3.1                   84.3           53.1
1               2          3.7                   87.8           61.3
2               3          7.9                   65.5           89.6
3               4          1.1                   58.1           41.6
4               5          1.3                   61.0           25.4
...           ...          ...                    ...            ...
24995       12047          1.8                   55.2           46.1
24996        1102          2.7                   97.1           56.5
24997        4422          1.0                   63.0           36.7
24998        7858          1.0                   69.4           34.1
24999       11621          0.7                   60.3           31.4

       final_grade
0                1
1                1
2                1
3                1
4                0
...            ...
24995            1
24996            1
24997            0
24998            0
24999            0

[25000 rows x 5 columns]

In [9]:
# taking data as input and output
inp=df.iloc[:,:4]
out=df.iloc[:,4:]

In [10]:
out.head()

   final_grade
0            1
1            1
2            1
3            1
4            0

## train-test split
splitting the data for training and testing and scaling them

In [11]:
from sklearn.model_selection import train_test_split as tts
inp_tr,inp_te,out_tr,out_te=tts(inp,out,test_size=0.3)

In [12]:
out_tr

       final_grade
7748             1
10408            1
17324            1
7616             1
22968            1
...            ...
22813            1
19378            1
9305             1
6084             1
13521            0

[17500 rows x 1 columns]

## SCALING

In [13]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
inp_tr=ss.fit_transform(inp_tr)

In [14]:
inp_tr

array([[ 0.06675561,  1.13872678, -1.57460112,  0.57303544],
       [ 0.68148848,  0.30662154,  1.23574777,  0.76834765],
       [-0.18838165,  0.86135836,  0.93662648,  0.75779023],
       ...,
       [ 0.42658233, -0.20188722, -1.67198945, -0.7466416 ],
       [-0.3177991 ,  0.49153381,  1.22183516,  0.48329741],
       [ 1.40091083, -1.17267667, -1.5606885 , -1.43815237]],
      shape=(17500, 4))

In [15]:
inp_te=ss.fit_transform(inp_te)

## MODEL TRAINING
using KNN and logistic regression for this dataset

In [16]:
from sklearn.linear_model import LogisticRegression
BP=LogisticRegression()
BP.fit(inp_tr,out_tr)

C:\Users\goura\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [17]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(inp_tr,out_tr)

C:\Users\goura\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:243: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier()

## TESTING

In [18]:
BP.predict(inp_te)

array([1, 1, 0, ..., 1, 1, 1], shape=(7500,))

In [19]:
knn.predict(inp_te)

array([1, 1, 0, ..., 1, 1, 1], shape=(7500,))

In [20]:
from sklearn.metrics import accuracy_score as acs
BPT=BP.predict(inp_te)
KNNT=knn.predict(inp_te)
acs1=acs(BPT,out_te)
acs2=acs(KNNT,out_te)
print(BPT)
print(KNNT)
print(acs1)
print(acs2)

[1 1 0 ... 1 1 1]
[1 1 0 ... 1 1 1]
0.9949333333333333
0.9893333333333333

In [22]:
print(BP.coef_)

[[ 0.09925222  0.79956294  0.26027287 18.65968166]]

## VISUALIZATION

In [35]:
from sklearn.metrics import confusion_matrix
CM1=confusion_matrix(out_te,BPT)
CM2=confusion_matrix(out_te,KNNT)
print(CM1)
print(CM2)

[[ 874   17]
 [   2 6607]]
[[ 847   44]
 [  28 6581]]

## model packaging

In [ ]:
import pickle